CREATE DATABASE IF NOT EXISTS neoforge
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_general_ci;

USE neoforge;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    role ENUM("admin", "user") DEFAULT "user",
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE games (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    developer VARCHAR(255) DEFAULT NULL,
    genre VARCHAR(100) DEFAULT NULL,
    price DECIMAL(10,2) DEFAULT NULL CHECK (price >= 0),
    platforms JSON DEFAULT NULL,
    rating DECIMAL(3,1) DEFAULT NULL CHECK (rating >= 0 AND rating <= 10),
    stock INT DEFAULT 0 CHECK (stock >= 0),
    created_by INT DEFAULT NULL,
    updated_by INT DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,

    CONSTRAINT fk_games_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_games_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;